# -*- coding: utf-8 -*-
#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by synthtool. DO NOT EDIT!

from __future__ import absolute_import
import os
import shutil

import nox


BLACK_VERSION = u"black==19.10b0"
BLACK_PATHS = [u"docs", u"google", u"tests", u"noxfile.py", u"setup.py"]

DEFAULT_PYTHON_VERSION = u"3.8"
SYSTEM_TEST_PYTHON_VERSIONS = [u"3.8"]
UNIT_TEST_PYTHON_VERSIONS = [u"3.6", u"3.7", u"3.8"]


@nox.session(python=DEFAULT_PYTHON_VERSION)
def lint(session):
    u"""Run linters.

    Returns a failure if the linters find linting errors or sufficiently
    serious code quality issues.
    """
    session.install(u"flake8", BLACK_VERSION)
    session.run(
        u"black", u"--check", *BLACK_PATHS,
    )
    session.run(u"flake8", u"google", u"tests")


@nox.session(python=u"3.6")
def blacken(session):
    u"""Run black.

    Format code to uniform standard.

    This currently uses Python 3.6 due to the automated Kokoro run of synthtool.
    That run uses an image that doesn't have 3.6 installed. Before updating this
    check the state of the `gcp_ubuntu_config` we use for that Kokoro run.
    """
    session.install(BLACK_VERSION)
    session.run(
        u"black", *BLACK_PATHS,
    )


@nox.session(python=DEFAULT_PYTHON_VERSION)
def lint_setup_py(session):
    u"""Verify that setup.py is valid (including RST check)."""
    session.install(u"docutils", u"pygments")
    session.run(u"python", u"setup.py", u"check", u"--restructuredtext", u"--strict")


def default(session):
    # Install all test dependencies, then install this package in-place.
    session.install(u"asyncmock", u"pytest-asyncio")

    session.install(u"mock", u"pytest", u"pytest-cov", u"sqlparse")
    session.install(u"-e", u".")

    # Run py.test against the unit tests.
    session.run(
        u"py.test",
        u"--quiet",
        u"--cov=google.cloud.spanner",
        u"--cov=google.cloud",
        u"--cov=tests.unit",
        u"--cov-append",
        u"--cov-config=.coveragerc",
        u"--cov-report=",
        u"--cov-fail-under=0",
        os.path.join(u"tests", u"unit"),
        *session.posargs,
    )

    session.install(u"-e", u".[tracing]")

    # Run py.test against the unit tests with OpenTelemetry.
    session.run(
        u"py.test",
        u"--quiet",
        u"--cov=google.cloud.spanner",
        u"--cov=google.cloud",
        u"--cov=tests.unit",
        u"--cov-append",
        u"--cov-config=.coveragerc",
        u"--cov-report=",
        u"--cov-fail-under=0",
        os.path.join(u"tests", u"unit"),
        *session.posargs,
    )


@nox.session(python=UNIT_TEST_PYTHON_VERSIONS)
def unit(session):
    u"""Run the unit test suite."""
    default(session)


@nox.session(python=SYSTEM_TEST_PYTHON_VERSIONS)
def system(session):
    u"""Run the system test suite."""
    system_test_path = os.path.join(u"tests", u"system.py")
    system_test_folder_path = os.path.join(u"tests", u"system")

    # Check the value of `RUN_SYSTEM_TESTS` env var. It defaults to true.
    if os.environ.get(u"RUN_SYSTEM_TESTS", u"true") == u"false":
        session.skip(u"RUN_SYSTEM_TESTS is set to false, skipping")
    # Sanity check: Only run tests if the environment variable is set.
    if not os.environ.get(u"GOOGLE_APPLICATION_CREDENTIALS", u"") and not os.environ.get(
        u"SPANNER_EMULATOR_HOST", u""
    ):
        session.skip(
            u"Credentials or emulator host must be set via environment variable"
        )

    system_test_exists = os.path.exists(system_test_path)
    system_test_folder_exists = os.path.exists(system_test_folder_path)
    # Sanity check: only run tests if found.
    if not system_test_exists and not system_test_folder_exists:
        session.skip(u"System tests were not found")

    # Use pre-release gRPC for system tests.
    session.install(u"--pre", u"grpcio")

    # Install all test dependencies, then install this package into the
    # virtualenv's dist-packages.
    session.install(
        u"mock", u"pytest", u"google-cloud-testutils",
    )
    session.install(u"-e", u".[tracing]")

    # Run py.test against the system tests.
    if system_test_exists:
        session.run(u"py.test", u"--quiet", system_test_path, *session.posargs)
    if system_test_folder_exists:
        session.run(u"py.test", u"--quiet", system_test_folder_path, *session.posargs)


@nox.session(python=DEFAULT_PYTHON_VERSION)
def cover(session):
    u"""Run the final coverage report.

    This outputs the coverage report aggregating coverage from the unit
    test runs (not system test runs), and then erases coverage data.
    """
    session.install(u"coverage", u"pytest-cov")
    session.run(u"coverage", u"report", u"--show-missing", u"--fail-under=99")

    session.run(u"coverage", u"erase")


@nox.session(python=DEFAULT_PYTHON_VERSION)
def docs(session):
    u"""Build the docs for this library."""

    session.install(u"-e", u".[tracing]")
    session.install(u"sphinx", u"alabaster", u"recommonmark")

    shutil.rmtree(os.path.join(u"docs", u"_build"), ignore_errors=True)
    session.run(
        u"sphinx-build",
        u"-W",  # warnings as errors
        u"-T",  # show full traceback on exception
        u"-N",  # no colors
        u"-b",
        u"html",
        u"-d",
        os.path.join(u"docs", u"_build", u"doctrees", u""),
        os.path.join(u"docs", u""),
        os.path.join(u"docs", u"_build", u"html", u""),
    )


@nox.session(python=DEFAULT_PYTHON_VERSION)
def docfx(session):
    u"""Build the docfx yaml files for this library."""

    session.install(u"-e", u".[tracing]")
    # sphinx-docfx-yaml supports up to sphinx version 1.5.5.
    # https://github.com/docascode/sphinx-docfx-yaml/issues/97
    session.install(u"sphinx==1.5.5", u"alabaster", u"recommonmark", u"sphinx-docfx-yaml")

    shutil.rmtree(os.path.join(u"docs", u"_build"), ignore_errors=True)
    session.run(
        u"sphinx-build",
        u"-T",  # show full traceback on exception
        u"-N",  # no colors
        u"-D",
        (
            u"extensions=sphinx.ext.autodoc,"
            u"sphinx.ext.autosummary,"
            u"docfx_yaml.extension,"
            u"sphinx.ext.intersphinx,"
            u"sphinx.ext.coverage,"
            u"sphinx.ext.napoleon,"
            u"sphinx.ext.todo,"
            u"sphinx.ext.viewcode,"
            u"recommonmark"
        ),
        u"-b",
        u"html",
        u"-d",
        os.path.join(u"docs", u"_build", u"doctrees", u""),
        os.path.join(u"docs", u""),
        os.path.join(u"docs", u"_build", u"html", u""),
    )
